<?xml version="1.0" encoding="utf-8"?><Database Name="locateme" Class="LocateMeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=locateme;Integrated Security=True" SettingsObjectName="DC.Properties.Settings" SettingsPropertyName="locatemeConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.locRegions" Member="locRegions">
    <Type Name="locRegion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.locCities" Member="locCities">
    <Type Name="locCity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CityType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.locStreets" Member="locStreets">
    <Type Name="locStreet">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="StreetType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PostIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>